version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs:ro
    networks:
      - iot-net
    restart: unless-stopped

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    volumes:
      - ./suricata/rules:/etc/suricata/rules
      - suricata-logs:/var/log/suricata
    command:
      - suricata
      - -c
      - /etc/suricata/suricata.yaml
      - -i
      - ens5
      - -l
      - /var/log/suricata
      - --set
      - rule-files.0=/etc/suricata/rules/local.rules
      - --set
      - rule-files.1=/etc/suricata/rules/mqtt-rate-limit.rules
      - --set
      - rule-files.2=/etc/suricata/rules/mqtt-malformed-json.rules
    depends_on:
      - mosquitto
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - suricata-logs:/suricata-logs:ro
    depends_on:
      - suricata
      - logstash
    networks:
      - iot-net
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - iot-net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - iot-net
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    networks:
      - iot-net
    restart: unless-stopped

networks:
  iot-net:
    driver: bridge

volumes:
  suricata-logs:
